### ISSUE TITLE
Failed to open file "./assets/shader/bin/frag.spv"

### ISSUE THREAD

**Issue by ArtemkaKun** [LouisSchmieder/engine#2]
I want to run example stuff. After tinkering and errors resolving I have an error 
```
V panic: failed to open file "./assets/shader/bin/frag.spv"
```
The problem is that there is no *frag.spv* file in the folder *assets*. Did you forget to push it or something?

**Comment by LouisSchmieder** [comment]
In the assets folder the is a V Script which just needs to be executed
